name: "Feature request"
description: "Suggest an idea for this project"
title: "[FR]: "
labels: ["enhancement"]
assignees:
    - Mara-Li
body:
    - type: markdown
      attributes:
          value: Thanks for taking the time to fill out this Feature request!
    - type: checkboxes
      attributes:
          label: Issue validation
          description: |
            - Thanks to check if your issue is relative to the repository. Any non relative or duplicate issue will be closed.
            - Please, check the documentation and the configuration files before submitting your request.
            - Issue not in English will be closed.

            > [!WARNING]
            > The code is not my own, so I can't guarantee I can fix everything, as I barely understand some part of it. 
            > As the plugin is heavy experimental, you should understand that most of the time, I can't accept the request, or it will take a long time to be implemented.
            > Moreover, it patch some part of the internal code of Obsidian, and can break some part of it, or broke at any update of Obsidian. 
          options:
              - label: "I checked the issue to prevent duplicate"
                required: true
              - label: "I checked my configurations files and the documentation"
                required: true
    - type: textarea
      id: describe-request
      attributes:
          label: Is your feature related to a problem ?
          description: If you found a solution with the inherent limit I had with Obsidian, please, add it here!
          placeholder: "Tell me the original problem"
    - type: textarea
      id: describe-solution
      attributes:
          label: What solution do you want to see ?
          description: Describe your idea here!
      validations:
          required: true
    - type: textarea
      id: alternative
      attributes:
          label: Describe the alternative you've considered
    - type: textarea
      attributes:
          label: Anything else?
          description: |
              Links? References? Anything that will give us more context about the issue you are encountering!
              Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      validations:
          required: false
    - type: markdown
      attributes:
          value: |
              ## Environment
              Please fill out the following information about your environment. If you are unsure about any of them, just leave it blank.
    - type: dropdown
      id: version
      attributes:
          label: OS
          description: Check your OS
          multiple: true
          options:
              - IOS
              - Android
              - MacOS
              - Windows
              - Linux
    - type: textarea
      attributes:
          label: Obsidian information
          description: |
              Please copy and paste the information about your Obsidian version using the command "show debug info" in the obsidian's commands palette.
          render: bash session
      validations:
          required: true
    - type: input
      id: plugin-version
      attributes:
          label: Plugin version
          description: Please copy and paste the version of the plugin you are using.
          placeholder: "1.0.0"
      validations:
          required: true